
// AppMessage keys:
enum {
	KEY_WEATHER_REQUEST = 0,
	KEY_WEATHER_TEMP_C,
	KEY_WEATHER_RAINCHANCE_PCT,
	KEY_WEATHER_CONDITIONS,
	KEY_WEATHER_HUMIDITY,
	KEY_WEATHER_ICON
};

// Persistent storage keys:
enum {
	PERSIST_WEATHER_TEMP_C = 0,
	PERSIST_WEATHER_RAINCHANCE_PCT,
	PERSIST_WEATHER_CONDITIONS,
	PERSIST_WEATHER_HUMIDITY,
	PERSIST_WEATHER_ICON,
	PERSIST_WEATHER_TIME_UPDATED,
};
