#ifndef CONSTANTS_H
#define CONSTANTS_H

// AppMessage keys:
enum {
	KEY_WEATHER_REQUEST = 0,
	KEY_WEATHER_TEMP_C,
	KEY_WEATHER_RAINCHANCE_PCT,
	KEY_WEATHER_CONDITIONS,
	KEY_WEATHER_HUMIDITY,
	KEY_WEATHER_ICON,

	KEY_PREF_SHOW_SECOND_HAND,
	KEY_PREF_SHOW_NO_CONNECTION,

	KEY_PREF_VIBRATE_ON_HOUR,
	KEY_PREF_VIBRATE_ON_DISCONNECT,

	KEY_PREF_LEFT_COMPLICATION,
	KEY_PREF_BOTTOM_COMPLICATION,
	KEY_PREF_RIGHT_COMPLICATION,

	KEY_PREF_LEFT_COMPLICATION_OPT1,
	KEY_PREF_LEFT_COMPLICATION_OPT2,
	KEY_PREF_LEFT_COMPLICATION_OPT3,
	KEY_PREF_LEFT_COMPLICATION_OPT4,
	KEY_PREF_BOTTOM_COMPLICATION_OPT1,
	KEY_PREF_BOTTOM_COMPLICATION_OPT2,
	KEY_PREF_BOTTOM_COMPLICATION_OPT3,
	KEY_PREF_BOTTOM_COMPLICATION_OPT4,
	KEY_PREF_RIGHT_COMPLICATION_OPT1,
	KEY_PREF_RIGHT_COMPLICATION_OPT2,
	KEY_PREF_RIGHT_COMPLICATION_OPT3,
	KEY_PREF_RIGHT_COMPLICATION_OPT4,

	KEY_PREF_VIBRATE_ON_CONNECT,

	KEY_PREF_THEME,

	KEY_PREF_QUIET_DURING_SLEEP,

	KEY_PREFS_REQUEST,
	KEY_PREFS_DONT_EXIST,

	KEY_PREF_SHOW_ANIMATIONS,

	KEY_PREF_TOP_COMPLICATION,
	KEY_PREF_TOP_COMPLICATION_OPT1,
	KEY_PREF_TOP_COMPLICATION_OPT2,
	KEY_PREF_TOP_COMPLICATION_OPT3,
	KEY_PREF_TOP_COMPLICATION_OPT4,

	KEY_PREF_QUIET_DURING_DND,
};

// Persistent storage keys:
enum {
	// Removed: 30 deprecated keys, so this list starts at 30
	PERSIST_PREFS_STRUCT = 30,
	PERSIST_WEATHER_STRUCT,
};

#endif
